//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3603
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace danmaq.Nineball.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("danmaq.Nineball.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   取得出来ませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESC_FAILED {
            get {
                return ResourceManager.GetString("DESC_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESC_NULL {
            get {
                return ResourceManager.GetString("DESC_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされたレイヤを変更することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_LOCKED_LAYER {
            get {
                return ResourceManager.GetString("ERR_LOCKED_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   danmaq Nineball-Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft DirectX 9.0c update(June 2008) 以降 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string REQ_DIRECTX {
            get {
                return ResourceManager.GetString("REQ_DIRECTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft .NET Framework 2.0以降 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string REQ_DOTNET {
            get {
                return ResourceManager.GetString("REQ_DOTNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Windows XP SP3以降 または Microsoft WindowsVista SP1以降 または Microsoft XBOX360 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string REQ_OS {
            get {
                return ResourceManager.GetString("REQ_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft XNA Framework 3.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string REQ_XNA {
            get {
                return ResourceManager.GetString("REQ_XNA", resourceCulture);
            }
        }
    }
}
