//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5456
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace danmaq.nineball.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("danmaq.nineball.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   設定・書き込みはサポートしません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLASS_ERR_READONLY {
            get {
                return ResourceManager.GetString("CLASS_ERR_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}オブジェクトを、2つ以上作ることはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLASS_ERR_SINGLETON {
            get {
                return ResourceManager.GetString("CLASS_ERR_SINGLETON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画に使用するSpriteBatchがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DRAW_ERR_SPRITEBATCH {
            get {
                return ResourceManager.GetString("DRAW_ERR_SPRITEBATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しない不具合が発生した為、ゲームを強制終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GENERAL_ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("GENERAL_ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の解放に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GENERAL_ERR_RELEASE {
            get {
                return ResourceManager.GetString("GENERAL_ERR_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は初期化されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GENERAL_INFO_INITIALIZED {
            get {
                return ResourceManager.GetString("GENERAL_INFO_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このゲームパッドは初期化に失敗したため、使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INPUT_ERR_LEGACY_INIT_FAILED {
            get {
                return ResourceManager.GetString("INPUT_ERR_LEGACY_INIT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このゲームパッドは初期化に失敗したため、使用できないかもしれません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INPUT_ERR_LEGACY_INIT_FAILED_MAYBE {
            get {
                return ResourceManager.GetString("INPUT_ERR_LEGACY_INIT_FAILED_MAYBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センタリング機能を設定できませんでした。
        ///このゲームパッドでは、フォース フィードバックは使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INPUT_WARN_LEGACY_CENTER {
            get {
                return ResourceManager.GetString("INPUT_WARN_LEGACY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共有モードで再設定を試みます。
        ///このモードでは、フォース フィードバックは使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INPUT_WARN_LEGACY_COOP {
            get {
                return ResourceManager.GetString("INPUT_WARN_LEGACY_COOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ ハンドルが指定されていないため、ゲームパッドを排他モードに設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INPUT_WARN_LEGACY_EXCLUSIVE {
            get {
                return ResourceManager.GetString("INPUT_WARN_LEGACY_EXCLUSIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション タイトルの変更はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_ERR_MODIFY_TITLE {
            get {
                return ResourceManager.GetString("IO_ERR_MODIFY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   多重起動されました。
        ///このアプリケーションは多重起動に対応しておりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_ERR_MUTEX {
            get {
                return ResourceManager.GetString("IO_ERR_MUTEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンテンツ マネージャが初期化されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_ERR_NULL_MGR_CONTENT {
            get {
                return ResourceManager.GetString("IO_ERR_NULL_MGR_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を{1}へ読み込みました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_INFO_LOADED {
            get {
                return ResourceManager.GetString("IO_INFO_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を{1}へ読込しています...。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_INFO_LOADING {
            get {
                return ResourceManager.GetString("IO_INFO_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を{1}への保存に{2}しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_INFO_SAVED {
            get {
                return ResourceManager.GetString("IO_INFO_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を{1}へ保存しています...。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_INFO_SAVING {
            get {
                return ResourceManager.GetString("IO_INFO_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した補助記憶装置に{0}が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_WARN_NOT_FOUND {
            get {
                return ResourceManager.GetString("IO_WARN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定データに互換性がありません。解決するためにデータをリセットします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IO_WARN_XML_COLLISION {
            get {
                return ResourceManager.GetString("IO_WARN_XML_COLLISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーマー サービスを起動できませんでした。
        ///ダイアログ・ストレージ選択機能はWindowsの機能で代用します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIVE_WARN_FAILED {
            get {
                return ResourceManager.GetString("LIVE_WARN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   danmaq Nineball Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NULL {
            get {
                return ResourceManager.GetString("NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STDOUT {
            get {
                return ResourceManager.GetString("STDOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUCCEEDED {
            get {
                return ResourceManager.GetString("SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テクスチャのピクセル フォーマットが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEX_ERR_FORMAT {
            get {
                return ResourceManager.GetString("TEX_ERR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現行のバージョンのXBOX360版では、ログ出力先を標準出力以外に設定することができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TRACE_ERR_CHANGE_FAILED {
            get {
                return ResourceManager.GetString("TRACE_ERR_CHANGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先を切り替えることが出来ませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TRACE_INFO_CHANGE_FAILED {
            get {
                return ResourceManager.GetString("TRACE_INFO_CHANGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先が切り替わりました。
        ///以前の出力先は {0} で、現在の変更された出力先は {1} です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TRACE_INFO_CHANGE_SUCCEEDED {
            get {
                return ResourceManager.GetString("TRACE_INFO_CHANGE_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ出力開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TRACE_INFO_START {
            get {
                return ResourceManager.GetString("TRACE_INFO_START", resourceCulture);
            }
        }
    }
}
