//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4927
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace danmaq.ball.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("danmaq.ball.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (C)1994-2010 Mc/danmaq All rights reserved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CREDIT {
            get {
                return ResourceManager.GetString("CREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   難易度を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESC_LEVEL {
            get {
                return ResourceManager.GetString("DESC_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIR_CONTENT {
            get {
                return ResourceManager.GetString("DIR_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bootlog.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_BOOTLOG {
            get {
                return ResourceManager.GetString("FILE_BOOTLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FONT_98 {
            get {
                return ResourceManager.GetString("FONT_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cursor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FX_CURSOR {
            get {
                return ResourceManager.GetString("FX_CURSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   partPointSprite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FX_PART_POINT_SPRITE {
            get {
                return ResourceManager.GetString("FX_PART_POINT_SPRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   logo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMAGE_LOGO {
            get {
                return ResourceManager.GetString("IMAGE_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウントダウン画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCENE_COUNTDOWN {
            get {
                return ResourceManager.GetString("SCENE_COUNTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クレジット画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCENE_CREDIT {
            get {
                return ResourceManager.GetString("SCENE_CREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCENE_GAME {
            get {
                return ResourceManager.GetString("SCENE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCENE_INITIALIZE {
            get {
                return ResourceManager.GetString("SCENE_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCENE_TITLE {
            get {
                return ResourceManager.GetString("SCENE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   赤い玉 青い玉 競走ゲーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
